### ISSUE TITLE
Export report as PDF through print.

### ISSUE THREAD

**Issue by peter-tanner** [uwasystemhealth/fracas_team2#53]
On view report

- [x] Button which calls CTRL+P to print to PDF
- [x] Remove some elements from the printing, search hide from print css or mui on google.
```css
@media print
{    
    button
    {
        display: none !important;
    }
}
```
